backend:
  name: git-gateway
  branch: master

media_folder: 'static/image'
public_folder: '/image'

collections:
  - name: 'price'
    label: 'Price'
    folder: 'content/price'
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
