backend:
  name: git-gateway
  repo: GoWeb-Internship/be-better
  branch: master

media_folder: 'static/image'
public_folder: '/image'

collections:
  # Price
  - name: 'price'
    label: 'Price'
    folder: 'content/price'
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'string' }
      - { label: 'Economy', name: 'economy', widget: 'string', required: false }
      - { label: 'Month', name: 'month', widget: 'string' }
      - { label: 'Hour', name: 'hour', widget: 'string' }
  #history clients
  - name: 'history'
    label: 'History'
    folder: 'content/clientHistory'
    create: true
    delete: true
    slug: '{{name-en}}-{{en-position}}'
    editor:
      preview: true
    fields:
      - { label: 'Name Ua', name: 'ukName', widget: 'string' }
      - { label: 'Position Ua', name: 'ukPosition', widget: 'string' }
      - { label: 'Text Ua', name: 'ukText', widget: 'string' }
      - { label: 'Name En', name: 'enName', widget: 'string' }
      - { label: 'Position En', name: 'enPosition', widget: 'string' }
      - { label: 'Text En', name: 'enText', widget: 'string' }
      - { label: 'Name Ru', name: 'ruName', widget: 'string' }
      - { label: 'Position Ru', name: 'ruPosition', widget: 'string' }
      - { label: 'Text Ru', name: 'ruText', widget: 'string' }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  # - name: 'aboutMe'
  #   label: 'About me'
  #   folder: 'content/aboutMe'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: 'aboutYou'
  #   label: 'About you'
  #   folder: 'content/aboutYou'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: 'route'
  #   label: 'Route'
  #   folder: 'content/route'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: 'guarantee'
  #   label: 'Guarantee'
  #   folder: 'content/guarantee'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: 'wyCouchBetter'
  #   label: 'Wy Couch Better'
  #   folder: 'content/wyCouchBetter'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }

  # - name: 'beBetter'
  #   label: 'Be Better'
  #   folder: 'content/beBetter'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: 'changes'
  #   label: 'Changes'
  #   folder: 'content/changes'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
