backend:
  name: git-gateway
  repo: GoWeb-Internship/be-better
  branch: master

media_folder: 'static/image'
public_folder: '/image'

collections:
  # Price
  - name: 'price'
    label: 'Price'
    folder: 'content/price'
    create: true
    delete: false
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Subscription Ua', name: 'ukSubscription', widget: 'string' }
      - { label: 'Subscription En', name: 'enSubscription', widget: 'string' }
      - { label: 'Subscription Ru', name: 'ruSubscription', widget: 'string' }
      - { label: 'Price Ua', name: 'ukPrice', widget: 'string' }
      - { label: 'Price En', name: 'enPrice', widget: 'string' }
      - { label: 'Price Ru', name: 'ruPrice', widget: 'string' }
      - { label: 'Economy Ua', name: 'ukEconomy', widget: 'string' }
      - { label: 'Economy En', name: 'enEconomy', widget: 'string' }
      - { label: 'Economy Ru', name: 'ruEconomy', widget: 'string' }
      - { label: 'Month Ua', name: 'ukMonth', widget: 'string' }
      - { label: 'Month En', name: 'enMonth', widget: 'string' }
      - { label: 'Month Ru', name: 'ruMonth', widget: 'string' }
      - { label: 'Hour Ua', name: 'ukHour', widget: 'string' }
      - { label: 'Hour En', name: 'enHour', widget: 'string' }
      - { label: 'Hour Ru', name: 'ruHour', widget: 'string' }
  #donats
  - name: 'donations'
    label: 'Donations'
    folder: 'content/donations'
    create: true
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Donations Ua', name: 'ukDonations', widget: 'string' }
      - { label: 'Donations En', name: 'enDonations', widget: 'string' }
      - { label: 'Donations Ru', name: 'ruDonations', widget: 'string' }
  #history clients
  - name: 'history'
    label: 'History'
    folder: 'content/clientHistory'
    create: true
    delete: true
    slug: '{{name-en}}-{{en-position}}'
    editor:
      preview: true
    fields:
      - { label: 'Name Ua', name: 'ukName', widget: 'string' }
      - { label: 'Position Ua', name: 'ukPosition', widget: 'string' }
      - { label: 'Text Ua', name: 'ukText', widget: 'string' }
      - { label: 'Name En', name: 'enName', widget: 'string' }
      - { label: 'Position En', name: 'enPosition', widget: 'string' }
      - { label: 'Text En', name: 'enText', widget: 'string' }
      - { label: 'Name Ru', name: 'ruName', widget: 'string' }
      - { label: 'Position Ru', name: 'ruPosition', widget: 'string' }
      - { label: 'Text Ru', name: 'ruText', widget: 'string' }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }

  # - name: 'aboutMe'
  #   label: 'About me'
  #   folder: 'content/aboutMe'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: 'aboutYou'
  #   label: 'About you'
  #   folder: 'content/aboutYou'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: 'route'
  #   label: 'Route'
  #   folder: 'content/route'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: 'guarantee'
  #   label: 'Guarantee'
  #   folder: 'content/guarantee'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: 'wyCouchBetter'
  #   label: 'Wy Couch Better'
  #   folder: 'content/wyCouchBetter'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }

  # - name: 'beBetter'
  #   label: 'Be Better'
  #   folder: 'content/beBetter'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: 'changes'
  #   label: 'Changes'
  #   folder: 'content/changes'
  #   create: false
  #   delete: false
  #   slug: '{{slug}}'
  #   editor:
  #     preview: true
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
